name: Cypress Tests

on: push
   
jobs:
  e2e-chrome-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: yarn install

      - name: E2E Tests - Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/*