name: Cypress Tests

on: [push]
   
jobs:
  e2e-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}